FROM caddy:2
COPY src/ /srv/
COPY Caddyfile.prod /etc/caddy/Caddyfile
# Build React frontend
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM caddy:2

COPY --from=build /app/dist /srv
COPY Caddyfile.prod /etc/caddy/Caddyfile