spring.application.name=reading_groups

# Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Token secret
jwt.secret=${JWT_SECRET}

# Public endpoints
app.public.paths=/api/auth/register,/api/auth/login,/swagger-ui/**,/v3/api-docs/**